language: python

# run tests for all envs
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
env: ISOLATED=false
install: pip install tox tox-travis
script: tox

# lint only needs run once
jobs:
  include:
    - python: 3.9
      env: ISOLATED=false
      install: pip install flake8
      script: flake8
